apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVVmR6b1d1ZElqN05kQVVtbnhkWGZEMS9nVzNNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXlNREV3T1RFNE1qWXhNbG9YRFRJeU1ESXdPREU0TWpZeE1sb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXUyNWNiK2sxY1JmeXcyaWxaZkVQVU9HRGF5NU5ER3ZsLzZ5QgpaYXRiSWJsOVlIU1BZNEQwcDFETGgrcnNpaEhZREIyNHBoNHlmUkZKVGFUZG1XT29pNDFORHBwa2YxT1ZCWGZKCnhReGlwOW81ekJTNTdtSnlUL25GZmg5RXYveXowaWNQWDBoRldqdkNmK0dUcUVrdkxUV3hpNEYwaTc3ZlNRUXcKQytqOUgwZmJTdXBKMlJ2bGt0N3hxdWdqcWR5V2sya0Fld3p0QUJPNUV1QXlqbzJxeUR2Y2NEMTVzZktFVHQ1TgptdjZNK1VlSTFGYXFKaEx1Mks0TjBZVE9pR1B6RXJhU1RxNW1GOW1TVjZ4bWZ0TFB1cTRrQmgzZ0xSeWJIWFRpClU4SGhRb21RS251VE0yMWhjd2RxRXlFVnB0OHppSHVLRWpweGZqck9ackM2RmRiZFp3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVM1pQRjNiUnhjVmZuc1N5cWdJaVc1THgreStRd0h3WURWUjBqQkJnd0ZvQVUzWlBGM2JSeApjVmZuc1N5cWdJaVc1THgreStRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFON3FXd2cxeUk0TG9WNzZpUk5RcHJHRjAxRHprZmk1WEI3QmhUNGNXZnlteUtYL1VINktoYUFvNmI2RHUKWWpXMStXa05nZzFmNFAvcTZ5aTlMMXZ5QkVZcWFYL1JKd2RuWGxLL0t3Q1ZzUWlKQk5lc2ZvOTQrSjdkcGxmdgpJeFlzRTlRWVd1VHNjb0RxdC9oWGZ3eC9zY3grQ3hQUXIvN2I3TXRDRXQ2ajh1bkVVNVNwOU0rM0F5OVdrQ1hwCkFzdHlwTk1LOHJ4cmVENXNTeE9ydEZ1KzlOby9ENFQ2WTA0bnZFVmxKaTlIbWxGTjJWL21tR29YOUhvT00ycGIKSHZmVE9kcTZIY25IcS9oT3JPcjh2b1FMQ083UWNRNEZFS2ZkakNGM1R1L0lNNTRsNzVZeWJHK2RxYVpEcy9VSApBd2tKaVNySlNFQ0RGTTBqd2tyVDVhb3BkZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]