apiVersion: v1
kind: Pod
metadata:
  labels:
    name: simple-webapp
  name: simple-webapp-2
spec:
  containers:
    - env:
        - name: APP_START_DELAY
          value: "80"
      image: kodekloud/webapp-delayed-start
      name: simple-webapp
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
      livenessProbe:
        httpGet:
          path: /live
          port: 8080
        initialDelaySeconds: 80
        periodSeconds: 1
        failureThreshold: 6
