apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front
  template:
    metadata:
      labels:
        tier: front
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine
