apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-example
  labels:
    name: example
spec:
  replicas: 10
  selector:
    matchLabels:
      name: example-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 10%
  template:
    metadata:
      labels:
        name: example-deploy
    spec:
      containers:
      - image: redis
        name: redis-example
        env:
          - name: SOME_ENV
            value: "Hello WORLD"
