apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: web-dashboard
    spec:
      containers:
        - image: kodekloud/my-kubernetes-dashboard
          imagePullPolicy: Always
          name: web-dashboard
          ports:
            - containerPort: 8080
              protocol: TCP
      serviceAccount: dashboard-sa
