apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-pod
  name: webapp-pod
spec:
  containers:
    - image: kodekloud/simple-webapp-mysql
      name: webapp-pod
      envFrom:
        - secretRef:
            name: db-secret
