apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTJlZjhTNjZBbS9LV2ZiWFJFeUw2aXlXZEh6aUN6WWVuUnlkenJ6UVRhQVd6CjArUVZnK3JDYUJEMCtrU1FrL3d3MVJpT1hsaU55M1l3djNZeFB5TlQyL2NHZVpocXpyb3NjeWVIRmdEdVUvenkKSGNKZWRZU3Z3S2RwL1o5NlJ3bEwxSTB4MWx5K3lVWHAxV0hRazVWaDQvSWtBcTlxYnNqamtkdDFuV2FwUm9kNQpDYlRHcFdEMmUrcmw4MnB6RnRrcG1ZaHRDbVpmdjBVQjluYkhueWdhVzh5MnR1Y1hhZlY0blE2Z2crVkt4bmVUCmU0a25JMjF4MEkrQU95V3NMMjJsRk9HcStFUTNzanhTR29Fcm56Y1dtMkEzUXJhL3M4NXlJTXdoUkV1VzdTSzYKTFZXNE5KZXovdWN3bURVc1pBbDlmend4NDZRUS9hNHpQSHNWY2kwRWZRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQXhZdktWYktiVmV6N3I4UzJ0TllvUkVwZC9nczBjM1pzRXc2ZHo2WStkNDVISlJBMmdECkxDMHhQQkduMU84NXhwSWw2ajQ2aFlzT1VxeVJ3dUJ1bFFzdi9xNGFIcks4dmtObUdrMmlCdmRkVU9Oa0xHV0gKNDNoaFRZU2pDRmJMTnBsdGNPMk5BQ0dkMnpMYVJVbW5TMWFaa1FGK0VXRGQyNXZQdVZIdGRKYlBicEE4MW1YSApSYlI3TkZORSs3cjBMMFlxTXp0R2JGVVE2ZXdtOVlyUVdGZE8xNFduTWZ4eVlNVDZLN3E4aWt4clo4U3R2VWVkCkU5a1kyTmIybHMwcjdnWHBpT2NyWWtqdXB0WG9OTFBDRVh0QTJ1RWJYNHpnMDJFTE43VDFaNFh1Vk1TOTgyMzkKNHl1Z0dCRTY5aEFQdDdvNnVGZWRFblFHL1JsbVJZZ2luZlk9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
